name: multimodal-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - numpy>=1.21.0
  - opencv>=4.5.0
  - scipy>=1.7.0
  - librosa>=0.9.0
  - libsndfile>=1.0.0
  - onnxruntime>=1.10.0
  - pip
  - pip:
    - pyaudio>=0.2.11
    - soundfile>=0.10.0
